### ISSUE TITLE
Is the library already production ready?

### ISSUE THREAD

**Issue by reksaandhika** [craftedbygc/taxi#1]
Hi, I was just exploring github and find out GC make new repo and it's interesting, you guys work always amaze me, this can be game changer for page transition, I really want to try this on my newest project (shopify project, because it's support reload JS on new page, might be good for external plugin shopify). But is taxi.js already production ready or better I just wait some time to make it more established for safety reasons? Thanks.

**Comment by jakewhiteley** [comment]
Hi @reksaandhika , thank you for the kind words!

It is production ready and has already been used some award winning websites ;)

As it is now publically available, we have bumped the version to reflect this - please use version `^1.0.0`.

**Comment by reksaandhika** [comment]
Thanks @jakewhiteley for clarifying. can I see a list of examples of websites that use taxi? I want to check and learn the behavior

**Comment by jakewhiteley** [comment]
The only website I can currently _share publicly_  is [Clou](https://www.clouarchitects.com/). I will have more to share soon and will get an examples page up on the docs website.

If it's ideas for behaviour you want, then have a look at [highway demos](https://highway.js.org/demos.html) or pretty much any site on [awwwards](https://www.awwwards.com/websites/) 😉
