### ISSUE TITLE
Anchors don't work 

### ISSUE THREAD

**Issue by tobimori** [craftedbygc/taxi#17]
If you follow a page link with Taxi that has an anchor, those aren't respected and the page url is set without anchor. 
(I don't expect the scrolling behaviour to be included, but to implement it myself I have to get the anchor which currently just gets ignored/replaced by Taxi)

**Comment by jakewhiteley** [comment]
@tobimori fixed in v1.5.1.

it was a regression introduced in 1.5.0 sorry.
