### ISSUE TITLE
Query about console message

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [craftedbygc/taxi#19]
When loading a new page, taxi outputs some information to the console:
![image](https://github.com/craftedbygc/taxi/assets/38588376/abae09e4-74b1-44c8-979a-853a6cb8d31d)
As you can see, it also states "ass". Why? Looking into the code via Chrome DevTools i see this:
![image](https://github.com/craftedbygc/taxi/assets/38588376/d1d72997-83bc-4534-84cc-8cf965dfda1a)
Why is it there?

**Comment by ThatBlockyPenguin** [comment]
Okay, oddly enough, after looking in the source code (under src/), it isn't there:
![image](https://github.com/craftedbygc/taxi/assets/38588376/bed0e509-7ecb-4c26-815b-569a623f59aa)
But once compiled into the dist/ directory, there it is:

![image](https://github.com/craftedbygc/taxi/assets/38588376/52afce9a-9a4f-452a-b5c2-f4e957832b84)
^taxi.umd.js

![image](https://github.com/craftedbygc/taxi/assets/38588376/5f5ea977-a198-4eb3-afaf-c9c4ab91f53d)
^taxi.modern.js

![image](https://github.com/craftedbygc/taxi/assets/38588376/8a49f491-91d6-460b-9b41-cd831d519d3f)
^taxi.js

![image](https://github.com/craftedbygc/taxi/assets/38588376/d101fb3e-bd62-44a7-b11d-1d09a2d88db7)
^taxi.esm.js

**Comment by jakewhiteley** [comment]
Fixed! Please pull 1.5.2 🍑

**Comment by ThatBlockyPenguin** [comment]
Thanks Jake! 😆
