### ISSUE TITLE
Scroll restoration

### ISSUE THREAD

**Issue by wiebekaai** [craftedbygc/taxi#20]
Hi, I'm for my page transitions both the old + new content are visible during the transitions. In my `onEnterCompleted` I clean this up.

The issue I have is that navigating scrolls to top but then does scroll restoration. Can I disable this fully or always scroll to top?

Thanks!

**Comment by wiebekaai** [comment]
Was overthinking it I guess `history.scrollRestoration = 'manual';`

**Comment by jakewhiteley** [comment]
Hi,

Yeah that is the approach I normally use as well!
