### ISSUE TITLE
Prefetched 404 breaks navigation

### ISSUE THREAD

**Issue by wiebekaai** [craftedbygc/taxi#21]
When prefetching 404s using my configuration, it throws a JavaScript error without displaying the 404 page to the user.

**To Reproduce**
1. Configure transition with `removeOldContent: false` and `bypassCache: true` (I remove old content in `onEnterCompleted()` of my renderer).
2. Hover a 404 link.
3. Click the link.
4. The `onLeave` transition is triggered, but it does not navigate to the 404 page.

This is how I remove old content:
```javascript
[...this.wrapper.querySelectorAll('[data-taxi-view]')].filter((e) => e !== this.content).forEach((e) => e.remove());
```

**Info**
 - Device: Macbook
 - OS: macOS Sonoma
 - Browser: Chrome
 - Version: 122

![Screen recording 2024-03-17 at 13 12 18@2x](https://github.com/craftedbygc/taxi/assets/17743878/bc0d9be0-017a-47bc-a691-65a493725429)

**Comment by jakewhiteley** [comment]
Can you confirm if this only happens with `removeOldContent: false`?

The console error is on purpose, but it should still navigate.

**Comment by jakewhiteley** [comment]
And the other question - is there any content on the 404 page (a 404 handler with a `[data-taxi-view]` present), or is it literally a 404 with no body returned?

**Comment by wiebekaai** [comment]
Even when I comment out all the code I have in the renderers except for calling `done()` the issue persists.

**Comment by jakewhiteley** [comment]
I will have to investigate further - I just tried on https://askphill.com/pages/services, and it navigated to the page using default browser navigation without getting stuck. Is it browser specific?

**Comment by wiebekaai** [comment]
What the hell. Having a hard time reproducing it now. I'll play around a bit and get back to you.

**Comment by jakewhiteley** [comment]
I've managed to reproduce. I'll come back to you when I know what's up!

**Comment by jakewhiteley** [comment]
@wiebekaai Coul you update to 1.5.3 and see if its still happening?

**Comment by wiebekaai** [comment]
> @wiebekaai Coul you update to 1.5.3 and see if its still happening?

Wow. Will do right now! Thanks so much 🙏 .

**Comment by wiebekaai** [comment]
It runs perfectly on the share theme link and production (we're using Shopify).

The local one has issues, which is less of a priority of course. Seems like the Shopify tracking pixels script does something with the fetch requests.

![Screen recording 2024-03-20 at 21 45 18@2x](https://github.com/craftedbygc/taxi/assets/17743878/c94be7ce-eb0d-404e-9e9f-73cba2a11b5c)

![Screen recording 2024-03-20 at 21 43 46@2x](https://github.com/craftedbygc/taxi/assets/17743878/f512bf9b-fa67-4c51-9630-da4f2751caa1)

**Comment by wiebekaai** [comment]
That's interesting, cool to see how this thing works. I'll open a new bug.

Yesssss, would be an honor :)!
