### ISSUE TITLE
Local Shopify 404 prefetching hangs

### ISSUE THREAD

**Issue by wiebekaai** [craftedbygc/taxi#22]
**Describe the bug**
Working with Shopify locally, prefetching 404s throws a JavaScript error without displaying the 404 page to the user. On production it works as expected and skips the transition, bringing you to the 404 page.

From my screenshots, the issue seems to be related to the way Shopify handles tracking (Web Pixel Manager). I'd be happy to show you an example setup in a screen share.

**To Reproduce**

- Configure transition with `removeOldContent: false` and `bypassCache: true` (remove old content in `onEnterCompleted()`).
- Use the [Shopify CLI](https://github.com/Shopify/cli?tab=readme-ov-file#developing-themes-with-shopify-cli) to start a project.
- Browse to the locally hosted Shopify theme (http://127.0.0.1:9292)
- Hover a 404 link.
- Click the link.
- The onLeave transition is triggered, but it does not navigate to the 404 page.

![image](https://github.com/craftedbygc/taxi/assets/17743878/ccf1b3cd-ca3a-4733-902a-9cfb5f629e20)
![image](https://github.com/craftedbygc/taxi/assets/17743878/3fa351bc-c4b3-444b-b22a-af71f3d5d1b7)

**Info**
- Device: Macbook
- OS: macOS Sonoma
- Browser: Chrome
- Version: 122

Follow up of https://github.com/craftedbygc/taxi/issues/21

**Comment by jakewhiteley** [comment]
Could I ask which taxi version this is? I assume the most recent

**Comment by wiebekaai** [comment]
> Could I ask which taxi version this is? I assume the most recent

Yes. Tried to reproduce and doesn't seem to happen anymore. Maybe I tried with a cached version before. Thanks again :).
