### ISSUE TITLE
Improve links option default value

### ISSUE THREAD

**Issue by andrepimpao** [craftedbygc/taxi#26]
This is more of a suggestion than an issue.

I came across a scenario where I had a third-party library to enable a debug bar on a project.

This debug bar was using `<a>` links for their tabs.
Unfortunately, these links had no `href` attribute and every time I clicked on them, Taxi.js would trigger a transition.

This was easily solved by setting the `links` option to `a[href]:not([target]):not([href^=\#]):not([data-taxi-ignore])`.

So, I just wanted to suggest adding that as the default `links` value, since it seems logical to me to only consider links with the `href` attribute (at least by default).

Thank you.

**Comment by andrepimpao** [comment]
(sorry, I didn't mean to label this as a bug, but I guess i used the "Bug report" template which did it for me and now I can't remove it)

**Comment by jakewhiteley** [comment]
@andrepimpao fixed in 1.7.1 👍 

Thank's for the report!
