### ISSUE TITLE
Renderer failed on rich content markup

### ISSUE THREAD

**Issue by reksaandhika** [craftedbygc/taxi#5]
Hi @jakewhiteley 
First thing, I really love the new update, I immediately update it, and of course my website transitions now faster!
But there's a (maybe) critical issue triggered, let me explain the about the bug.

**Describe the bug**
So I have an on-progress website, and I am trying to update the taxi.js to 1.1.0 to get a faster fetch transition benefit.
I tried the transition forward, and back, and I found taxi.js failed to render when there's a page with a lot of HTML (content).
Because I can't publish my WIP website, so I create the debug project, so you know why this happens.

You can try cloning my repo here:
[taxi-debug](https://github.com/reksaandhika/taxi-debug)

**To Reproduce**
1. Make HTML with lot of content (heading, description, input, images, etc)
2. Try navigating to that page (make sure you navigate from less content page -> rich content page)
3. If the bug is not triggered, repeat the number 2 step but on refresh position (because this bug only happens sometimes, but often enough)

Note:
If you try my repo, you can try navigation from home -> about and keep repeating if the bug is not triggered.
Make sure you refresh on home position if the bug is not triggered and repeat the navigation.

**Info**

https://user-images.githubusercontent.com/39384007/192044023-da5330d2-0def-4b45-a366-576162611252.mp4

**Device**
 - Device: PC Windows
 - OS: Windows
 - Browser: Google Chrome
 - Version: 105

Once again, thanks for keep improving the library, keep up the great work!

**Comment by jakewhiteley** [comment]
Hi @reksaandhika , sorry for the delay.

I will check this out today, but it looks like a markup issue on your side and not a Taxi issue, but I will let you know.

**Comment by jakewhiteley** [comment]
@reksaandhika I have clicked back and forth around 80 times now in your app, and never get the error :/ 

Could you try in incognito and see if it still happens?

**Comment by reksaandhika** [comment]
@jakewhiteley Maybe your internet too fast, you can try throttle your network on inspect element.

Or you can try my step:
1. Refresh page on homepage
2. After refresh, immediately go to "About" page

Note: don't let cursor hover too long on next page

https://user-images.githubusercontent.com/39384007/193636921-e1173442-ef55-4275-84b9-e504fac8f3a3.mp4

**Comment by reksaandhika** [comment]
Maybe HTML on server will help to found this bug.

I just deploy the project:
[https://taxi-debug.vercel.app/](https://taxi-debug.vercel.app/)

**Comment by reksaandhika** [comment]
@jakewhiteley Here is with incognito (private mode) on Firefox.
No extension running, and this happens also on Macbook and iPhone (I make sure it's not from my computer).

https://user-images.githubusercontent.com/39384007/193643907-4d2b98f9-5d85-4175-b060-3fedcceabc4e.mp4

**Comment by reksaandhika** [comment]
Ahh that's too bad.

I just like my `reloadJsFilter` preference like that, only load once for specific js only, even I remove that, the failed render still happen.

I don't get it when usually this happen, but mostly when "next page" not ready on hover and conflicted fetch onclick.

This is list error source from console log:

![image](https://user-images.githubusercontent.com/39384007/193647283-92bea148-2672-4f73-939d-821b923b37b3.png)

![image](https://user-images.githubusercontent.com/39384007/193647309-38959b0e-c4b1-4ddb-9bbc-9544c2814529.png)

![image](https://user-images.githubusercontent.com/39384007/193647337-5aaab1db-fe81-4699-b51a-745f7c957013.png)

![image](https://user-images.githubusercontent.com/39384007/193647372-33d7d521-dd21-4887-9783-011864e476a8.png)

**Comment by reksaandhika** [comment]
I think I found the problem, my `await delay()` on Transition onLeave seems like the problem. When I remove it, I never get the failed render. Is my code wrong to do delay like that for waiting transition? @jakewhiteley

**Comment by jakewhiteley** [comment]
Not really anything wrong no.

I would suggest something like 
```js
gsap.fromTo('.preload', {yPercent: 100}, {yPercent: 0,  display: 'flex'})
   .then(() => {
      done()
   })
```

or the tween's `onComplete` callback.

The thing is, I don't see a reason why it would be happening. Even when I throttled to basically no internet, I never encountered any race conditions - when the initial document is being fetched, the transition waits for this to finish before calling it's `enter` method.

On bigger or more complicated apps though, I would move your reveal animation into a transition and out of a renderer or you are creating a hard dependency between a renderer and a transition.

Another tip is I will enqueue things to load (images etc) on my renderer onEnter, and my transition onEnter will wait until all of these are resolved before resolving itself.

**Comment by jakewhiteley** [comment]
Let me know if you find the actual race condition or cause of this issue, and feel free to reopen this ticket or create a new one.

I am closing this for now.

**Comment by reksaandhika** [comment]
I can show you my WIP project, it's more easily to trigger the bug, can I contact you? maybe twitter DM, but your DMs closed @jakewhiteley
